# Generated by Django 4.2.6 on 2023-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='facebook_url',
        ),
        migrations.AddField(
            model_name='about',
            name='article_avatar',
            field=models.ImageField(default='default', upload_to='static/contactinfo/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='avatar',
            field=models.ImageField(upload_to='static/contactinfo/'),
        ),
    ]
