# Generated by Django 4.2.7 on 2023-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_about_post_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
