# Generated by Django 4.2.6 on 2023-10-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_comment_post_tag_delete_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
